### ISSUE TITLE
Filter returns error 1 with Mac 10.12, homebrew Pandoc 1.19.2.1, Python 2.7

### ISSUE THREAD

**Issue by p3palazzo** [bwhelm/pandoc-reference-filter#2]
````
pandoc -Ss --normalize --filter=internal-references --filter=pandoc-citeproc -o target.icml source.md
````
Returns for any output file format:

````
Traceback (most recent call last):
  File "/usr/local/bin/internal-references", line 11, in <module>
    load_entry_point('pandoc-internal-references==0.5.1', 'console_scripts', 'internal-references')()
  File "build/bdist.macosx-10.11-x86_64/egg/internalreferences.py", line 686, in main
  File "/usr/local/lib/python2.7/site-packages/pandocfilters.py", line 36, in walk
    obj[k] = walk(x[k], action, format, meta)
  File "/usr/local/lib/python2.7/site-packages/pandocfilters.py", line 36, in walk
    obj[k] = walk(x[k], action, format, meta)
  File "/usr/local/lib/python2.7/site-packages/pandocfilters.py", line 36, in walk
    obj[k] = walk(x[k], action, format, meta)
  File "/usr/local/lib/python2.7/site-packages/pandocfilters.py", line 22, in walk
    res = action(item['t'], item['c'], format, meta)
KeyError: 'c'
pandoc: Error running filter internal-references
Filter returned error status 1
````

**Comment by bwhelm** [comment]
Are you sure this error is produced by this filter? (This filter executable is `internalreferences.py`, not `internal-references`, as you have it.)

If so, can you provide a minimal example of an input file and pandoc options that produces this error?

**Comment by p3palazzo** [comment]
I used the following command after running the installer successfully:

````
pandoc --filter internal-references -o test.html test.md
````

Here is a test file that returns the error:

````
---
title:        Test
author:
- name:       Me
---

To test, look at Figure @fig:some.

![This is a figure caption](icon.png){#fig:some}

And some more text.
````

Here is the output from `python setup.py install`, which seems to be ok:

````
running install
running bdist_egg
running egg_info
writing requirements to pandoc_internal_references.egg-info/requires.txt
writing pandoc_internal_references.egg-info/PKG-INFO
writing top-level names to pandoc_internal_references.egg-info/top_level.txt
writing dependency_links to pandoc_internal_references.egg-info/dependency_links.txt
writing entry points to pandoc_internal_references.egg-info/entry_points.txt
reading manifest file 'pandoc_internal_references.egg-info/SOURCES.txt'
writing manifest file 'pandoc_internal_references.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-x86_64/egg
running install_lib
running build_py
creating build/bdist.macosx-10.11-x86_64/egg
copying build/lib/internalreferences.py -> build/bdist.macosx-10.11-x86_64/egg
byte-compiling build/bdist.macosx-10.11-x86_64/egg/internalreferences.py to internalreferences.pyc
creating build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pandoc_internal_references.egg-info/PKG-INFO -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pandoc_internal_references.egg-info/SOURCES.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pandoc_internal_references.egg-info/dependency_links.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pandoc_internal_references.egg-info/entry_points.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pandoc_internal_references.egg-info/requires.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
copying pandoc_internal_references.egg-info/top_level.txt -> build/bdist.macosx-10.11-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/pandoc_internal_references-0.5.1-py2.7.egg' and adding 'build/bdist.macosx-10.11-x86_64/egg' to it
removing 'build/bdist.macosx-10.11-x86_64/egg' (and everything under it)
Processing pandoc_internal_references-0.5.1-py2.7.egg
Removing /usr/local/lib/python2.7/site-packages/pandoc_internal_references-0.5.1-py2.7.egg
Copying pandoc_internal_references-0.5.1-py2.7.egg to /usr/local/lib/python2.7/site-packages
pandoc-internal-references 0.5.1 is already the active version in easy-install.pth
Installing internal-references script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/pandoc_internal_references-0.5.1-py2.7.egg
Processing dependencies for pandoc-internal-references==0.5.1
Searching for pandoc-attributes==0.1.7
Best match: pandoc-attributes 0.1.7
Processing pandoc_attributes-0.1.7-py2.7.egg
pandoc-attributes 0.1.7 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/site-packages/pandoc_attributes-0.1.7-py2.7.egg
Searching for pandocfilters==1.2.3
Best match: pandocfilters 1.2.3
Adding pandocfilters 1.2.3 to easy-install.pth file

Using /usr/local/lib/python2.7/site-packages
Finished processing dependencies for pandoc-internal-references==0.5.1
````

And `which internal-references` returns `/usr/local/bin/internal-references` as expected. I am running OSX 10.12.3, not sure if that makes a difference since I am using homebrew python.

**Comment by p3palazzo** [comment]
OK, got it, I was using the wrong version of pandocfilters.
